export const ADD_WORD = 'ADD_WORD';
<<<<<<< HEAD
export const SET_RIGHT_ANSWERS = 'SET_RIGHT_ANSWERS';
export const SET_BEST_SERIES = 'SET_BEST_SERIES';
export const ADD_RIGHT_ANSWER = 'ADD_RIGHT_ANSWER';
export const ADD_WRONG_ANSWER = 'ADD_WRONG_ANSWER';
=======
export const ADD_WORD_COUNT = 'ADD_WORD_COUNT';
export const ANSWERED_COUNT = 'ANSWERED_COUNT';
export const ANSWERED_CORRECT = 'ANSWERED_CORRECT';
export const ADD_HARD_WORD = 'ADD_HARD_WORD';
>>>>>>> 2fdc4fb66dd2ab938b374e242d3342d56e949b94
