export const ADD_WORD = 'ADD_WORD';
export const ADD_WORD_COUNT = 'ADD_WORD_COUNT';
export const ANSWERED_COUNT = 'ANSWERED_COUNT';
export const ANSWERED_CORRECT = 'ANSWERED_CORRECT';
export const ADD_HARD_WORD = 'ADD_HARD_WORD';
