export const ADD_WORD = 'ADD_WORD';
export const SET_RIGHT_ANSWERS = 'SET_RIGHT_ANSWERS';
export const SET_BEST_SERIES = 'SET_BEST_SERIES';
export const ADD_RIGHT_ANSWER = 'ADD_RIGHT_ANSWER';
export const ADD_WRONG_ANSWER = 'ADD_WRONG_ANSWER';